import type { SegmentReport } from './types';
import { fixed2 } from './money';
import { fmtDateTime, fmtDuration, TENDER_LABEL } from './format';

const W = 42;
const pad = (l: string, r: string) => l.slice(0, W - r.length - 1) + ' '.repeat(Math.max(1, W - Math.min(l.length, W - r.length - 1) - r.length)) + r;
const center = (s: string) => ' '.repeat(Math.max(0, Math.floor((W - s.length) / 2))) + s;
const rule = '-'.repeat(W);

/** Printable 80mm version of a segment / shift closing report. */
export function closingReportText(r: SegmentReport, storeName: string): string {
  const o: string[] = [];
  o.push(center(storeName.toUpperCase()));
  o.push(center(r.scope === 'shift' ? 'REPORTE DE CIERRE DE TURNO (Z)' : 'REPORTE DE CIERRE DE SEGMENTO'));
  o.push(rule);
  o.push(pad('Asociado', r.employeeName));
  o.push(pad('Caja', r.registerId));
  o.push(pad('Desde', fmtDateTime(r.startedAt)));
  o.push(pad('Hasta', fmtDateTime(r.endedAt)));
  o.push(pad('Duración', fmtDuration(r.durationMin)));
  o.push(rule);
  o.push(pad('Transacciones', String(r.transactions)));
  o.push(pad('Artículos vendidos', String(r.itemsSold)));
  o.push(pad('Ventas brutas', fixed2(r.grossSales)));
  o.push(pad('Descuentos en artículos', `-${fixed2(r.lineDiscounts)}`));
  o.push(pad('Descuentos en ventas', `-${fixed2(r.txnDiscounts)}`));
  o.push(pad('Devoluciones', `-${fixed2(r.returns)}`));
  o.push(pad('Ventas netas', fixed2(r.netSales)));
  o.push(pad('HST cobrado', fixed2(r.tax)));
  o.push(pad('TOTAL COBRADO', fixed2(r.total)));
  o.push(pad('Ticket promedio', fixed2(r.averageBasket)));
  o.push(rule);
  o.push(center('FORMAS DE PAGO'));
  for (const [k, v] of Object.entries(r.tenders)) if (v) o.push(pad(`${TENDER_LABEL[k] ?? k} (${v.count})`, fixed2(v.amount)));
  o.push(rule);
  o.push(center('CAJÓN DE EFECTIVO'));
  o.push(pad('Fondo inicial', fixed2(r.cash.openingFloat)));
  o.push(pad('Efectivo recibido', fixed2(r.cash.cashTendered)));
  o.push(pad('Cambio entregado', `-${fixed2(r.cash.changeGiven)}`));
  o.push(pad('Reembolsos en efectivo', `-${fixed2(r.cash.cashRefunds)}`));
  o.push(pad('Depósitos a caja fuerte', `-${fixed2(r.cash.drops)}`));
  o.push(pad('Pagos de gastos', `-${fixed2(r.cash.paidOuts)}`));
  o.push(pad('ESPERADO EN EL CAJÓN', fixed2(r.cash.expectedInDrawer)));
  o.push(rule);
  o.push(center('ACTIVIDAD'));
  o.push(pad('Artículos anulados', `${r.voids.lines} (${fixed2(r.voids.linesValue)})`));
  o.push(pad('Ventas anuladas', `${r.voids.transactions} (${fixed2(r.voids.transactionsValue)})`));
  o.push(pad('Sin venta (cajón)', String(r.noSales)));
  o.push(pad('Cambios de precio', String(r.priceOverrides)));
  o.push(pad('Descuentos aplicados', String(r.discountsApplied)));
  o.push(pad('Aprobaciones de gerente', String(r.managerOverrides)));
  o.push(pad('Códigos desconocidos', String(r.scanUnknown)));
  o.push(pad('Ventas en espera', String(r.holds)));
  o.push(rule);
  o.push(center('VENTAS POR CATEGORÍA'));
  for (const c of r.byCategory) o.push(pad(`${c.name} (${c.qty})`, fixed2(c.amount)));
  o.push(rule);
  o.push(center('ARTÍCULOS MÁS VENDIDOS'));
  for (const t of r.topItems.slice(0, 8)) o.push(pad(`${t.qty}x ${t.name}`, fixed2(t.amount)));
  o.push(rule);
  o.push(center(`Impreso ${fmtDateTime(new Date().toISOString())}`));
  return o.join('\n');
}
